// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIBqKB_rhL96lHQFwufYa1nMHWYMjh50',
    appId: '1:381146946885:android:cb16f55a4c3ad4593eb22c',
    messagingSenderId: '381146946885',
    projectId: 'go-shaban',
    storageBucket: 'go-shaban.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnXF2J3NCeYM-L2KwOc-YhgNnxHxCVag',
    appId: '1:381146946885:ios:ff3124c9becdef163eb22c',
    messagingSenderId: '381146946885',
    projectId: 'go-shaban',
    storageBucket: 'go-shaban.firebasestorage.app',
    iosBundleId: 'com.example.uber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDOwfk9U6PQoOWqMjyeiPlAcjh8ARB6Fg',
    appId: '1:381146946885:web:b9123d07fdcb9ea83eb22c',
    messagingSenderId: '381146946885',
    projectId: 'go-shaban',
    authDomain: 'go-shaban.firebaseapp.com',
    storageBucket: 'go-shaban.firebasestorage.app',
    measurementId: 'G-48FXPWSB3W',
  );
}
